version: '3'
services:
  dmtcp-service:
    image: dmtcp/dmtcp:latest
    restart: always
    environment:
      - DOMAIN=local
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
    
    
